### ISSUE TITLE
Add support for n-1 or n-2 (macOS 13 Ventura or macOS 12 Monterey)

### ISSUE THREAD

**Issue by bradtchapman** [jamf/Haversack#8]
https://github.com/jamf/Haversack/blob/5a3288db3549475b5b79e7897610c4857ce38958/.github/workflows/swift.yml#L14

This framework is one of two being used in the new Jamf Sync utility.  Please ensure that it can run on at least n-1 or n-2.

**Comment by macblazer** [comment]
The GitHub workflow you reference is where the unit tests are being run.

The Package.swift file describes the supported deployment OS versions for apps that use Haversack.

https://github.com/jamf/Haversack/blob/361e798ccc73edf1aeb1c265a6dcdde5a20f8132/Package.swift#L9C1-L15C7
